<font size="5">***numPy***</font>

In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [6]:
b[0]

np.float64(0.0)

In [7]:
b = np.array([0, .5, 1, 1.5, 2])

In [8]:
b[1]

np.float64(0.5)

In [9]:
a = np.array([1, 2, 3, 4])

In [10]:
a[1:]

array([2, 3, 4])

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [12]:
A.shape

(2, 3)

In [13]:
A.ndim

2

In [14]:
A.size

6

In [15]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [16]:
A[1]

array([4, 5, 6])

In [17]:
A[1][0]

np.int64(4)

In [18]:
A[1, 0]

np.int64(4)

In [19]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [22]:
A[:2, 2:]

array([[3],
       [6]])

In [23]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
A[1] = np.array([10, 10, 10])

In [25]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [26]:
A[2] = 99

In [27]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [28]:
#Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [29]:
A[1]

array([4, 5, 6])

In [30]:
A[1][0]

np.int64(4)

In [31]:
A[1, 0]

np.int64(4)

In [32]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [35]:
A[:2, 2:]

array([[3],
       [6]])

In [36]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
A[1] = np.array([10, 10, 10])

In [38]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [39]:
A[2] = 99

In [40]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [41]:
A[1][1] = 15

In [42]:
A

array([[ 1,  2,  3],
       [10, 15, 10],
       [99, 99, 99]])

In [43]:
A[2][2] = 45

In [44]:
A

array([[ 1,  2,  3],
       [10, 15, 10],
       [99, 99, 45]])

<font size="3">**Summary Statistics**</font>

In [45]:
a = np.array([1, 2, 3, 4])

In [46]:
a.sum()

np.int64(10)

In [47]:
a.mean()

np.float64(2.5)

In [48]:
a.std()

np.float64(1.118033988749895)

In [49]:
A

array([[ 1,  2,  3],
       [10, 15, 10],
       [99, 99, 45]])

In [50]:
A.sum()

np.int64(284)

In [51]:
A.mean()

np.float64(31.555555555555557)

In [52]:
A.std()

np.float64(38.15789160000883)

In [53]:
A.sum(axis=0)

array([110, 116,  58])

In [54]:
A.sum(axis=1)

array([  6,  35, 243])

In [55]:
A.mean(axis=0)

array([36.66666667, 38.66666667, 19.33333333])

In [56]:
A.mean(axis=1)

array([ 2.        , 11.66666667, 81.        ])

In [57]:
A.std(axis=0)

array([44.22920101, 42.99095512, 18.37268504])

In [58]:
A.std(axis=1)

array([ 0.81649658,  2.3570226 , 25.45584412])

<font size="3">**Broadcasting and Vectorized operations**</font>

In [59]:
a = np.arange(4)

In [60]:
a

array([0, 1, 2, 3])

In [61]:
a + 10

array([10, 11, 12, 13])

In [62]:
a * 10

array([ 0, 10, 20, 30])

In [63]:
a

array([0, 1, 2, 3])

In [64]:
a += 100

In [65]:
a

array([100, 101, 102, 103])

In [66]:
l = [0, 1, 2, 3]

In [67]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [68]:
a = np.arange(4)

In [69]:
a

array([0, 1, 2, 3])

In [70]:
b = np.array([10, 10, 10, 10])

In [71]:
b

array([10, 10, 10, 10])

In [72]:
c = a + b

In [73]:
c

array([10, 11, 12, 13])

In [74]:
d = a * b

In [75]:
d

array([ 0, 10, 20, 30])

In [76]:
e = c ** d

e

<font size="3">**Boolean arrays**</font>

In [77]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
a[[0, -1]]

array([0, 3])

In [81]:
a[[True, False, True, False]]

array([0, 2])

In [82]:
a >= 2

array([False, False,  True,  True])

In [83]:
a[a >= 2]

array([2, 3])

In [84]:
a.mean()

np.float64(1.5)

In [85]:
a[a > a.mean()]

array([2, 3])

In [86]:
a[~(a > a.mean())]

array([0, 1])

In [87]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [88]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [91]:
A = np.random.randint(100, size=(3, 3))

In [92]:
A

array([[77, 62, 38],
       [22, 96, 81],
       [73, 17, 82]], dtype=int32)

In [93]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([77, 38, 96, 73, 82], dtype=int32)

In [96]:
A > 30

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [97]:
A[A > 30]

array([77, 62, 38, 96, 81, 73, 82], dtype=int32)

<font size="3">**Linear Algebra**</font>

In [98]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [99]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [100]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [101]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [103]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

**SIZE OF OBJECTS IN MEMORY**

**Int, floats**

In [105]:
# An integer in python is > 24bytes
sys.getsizeof(1)

28

In [106]:
# Longs are even larger 
sys.getsizeof(10**100)

72

In [107]:
# NumPy size is much smaller
np.dtype(int).itemsize

8

In [108]:
# NumPy size is much smaller
np.dtype(np.int8).itemsize

1

**Lists are even larger**

# A one-element list
sys.getsizeof(1)

In [109]:
# An array of one element is bumpy
np.array([1]).nbytes

8

**And performance is also important**

In [110]:
l = list(range(1000))

In [111]:
a = np.arange(1000)

In [112]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 5.26 ms


np.int64(332833500)

In [113]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 13.8 ms


332833500

<font size="3">**USEFUL NUMPY FUNCTIONS**</font>

**random**

In [114]:
np.random.random(size = 2)

array([0.89301595, 0.2063429 ])

In [115]:
np.random.normal(size = 2)

array([ 1.91493349, -0.43533663])

In [116]:
np.random.rand(2, 4)

array([[0.75455085, 0.37195626, 0.01444552, 0.93073523],
       [0.76052837, 0.12364854, 0.82256983, 0.51226883]])

**arange**

In [117]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [119]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

**reshape**

In [120]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**linspace**

In [122]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

np.linspace(0, 1, 20)

In [123]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

**zeros, ones, empty**

In [124]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [125]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [127]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [128]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [130]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

**identity and eye**

In [61]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])