# Missing Data

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>

In [37]:
import numpy as np
import pandas as pd

What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated. For example, for a survey, a _`Salary`_ field with an empty value, or a number 0, or an invalid value (a string for example) can be considered "missing data". These concepts are related to the values that Python will consider "Falsy":

In [38]:
falsy_values = (0, False, None, '', [], {})

For Python, all the values above are considered "falsy":

In [39]:
any(falsy_values)

False

Numpy has a special "nullable" value for numbers which is `np.nan`. It's _NaN_: "Not a number"

In [40]:
np.nan

nan

The `np.nan` value is kind of a virus. Everything that it touches becomes `np.nan`:

In [41]:
3 + np.nan

nan

In [42]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [43]:
a.sum()

np.float64(nan)

In [44]:
a.mean()

np.float64(nan)

This is better than regular `None` values, which in the previous examples would have raised an exception:

3 + None

For a numeric array, the `None` value is replaced by `np.nan`:

In [45]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [46]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

As we said, `np.nan` is like a virus. If you have any `nan` value in an array and you try to perform an operation on it, you'll get unexpected results:

In [47]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [48]:
a.mean()

np.float64(nan)

In [49]:
a.sum()

np.float64(nan)

Numpy also supports an "Infinite" type:

In [50]:
np.inf

inf

Which also behaves as a virus:

In [51]:
3 + np.inf

inf

In [52]:
np.inf / 3

inf

In [53]:
np.inf / np.inf

nan

In [54]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)

In [55]:
b.sum()

np.float64(nan)

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>

### Checking for `nan` or `inf`

There are two functions: `np.isnan` and `np.isinf` that will perform the desired checks:

In [56]:
np.isnan(np.nan)

np.True_

In [57]:
np.isinf(np.inf)

np.True_

And the joint operation can be performed with `np.isfinite`.

In [58]:
np.isfinite(np.nan), np.isfinite(np.inf)

(np.False_, np.False_)

`np.isnan` and `np.isinf` also take arrays as inputs, and return boolean arrays as results:

In [59]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [60]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [61]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

_Note: It's not so common to find infinite values. From now on, we'll keep working with only `np.nan`_

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>


### Filtering them out

Whenever you're trying to perform an operation with a Numpy array and you know there might be missing values, you'll need to filter them out before proceeding, to avoid `nan` propagation. We'll use a combination of the previous `np.isnan` + boolean arrays for this purpose:

In [62]:
a = np.array([1,2, 3, np.nan, np.nan, 4])

In [63]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

Which is equivalent to:

In [64]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

And with that result, all the operation can be now performed:

In [65]:
a[np.isfinite(a)].sum()

np.float64(10.0)

In [66]:
a[np.isfinite(a)].mean()

np.float64(2.5)

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>